### ISSUE TITLE
Cannot run setup.js script

### ISSUE THREAD

**Issue by lucianoacsilva** [soramitsu/iroha-wallet-js#28]
Hello, 

When running the script **setup.js**, I got this error:

Error: Query response error: expected=ACCOUNT_RESPONSE, actual=ERROR_RESPONSE
Reason: {"reason":1,"message":"query signatories did not pass validation","errorCode":3}

I've already initialized Iroha and PostgresSQL DB. Someone knows what could be happening?

**Comment by Pobepto** [comment]
@lucianosilva44 Hi! Did you run iroha and postgresql via docker-compose?

**Comment by rockingeric** [comment]
Hello! I have the same issue, I followed Iroha documentation starting Iroha and PostgreSQL via docker run. Could you help me with that? Thank you!

I tried upgrading iroha-helpers to the latest and it didn't help.

This is a part of the output:

#### INFO ####
setting up accounts and assets with using '/root/iroha-wallet-js/scripts/wallets.json'
accounts: admin@iroha, alice@iroha
assets: AAAAA, DDDDD, CCCCC, BBBBB
#### INFO ####

trying to create an account: alice@iroha
Error: Query response error: expected=ACCOUNT_RESPONSE, actual=ERROR_RESPONSE
Reason: {"reason":1,"message":"query signatories did not pass validation","errorCode":3}
    at /root/iroha-wallet-js/node_modules/iroha-helpers/lib/queries/index.js:90:21
    at /root/iroha-wallet-js/node_modules/iroha-helpers/lib/queries/index.js:73:7
    at Object.onReceiveStatus (/root/iroha-wallet-js/node_modules/grpc/src/client_interceptors.js:1207:9)
    at InterceptingListener._callNext (/root/iroha-wallet-js/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/root/iroha-wallet-js/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/root/iroha-wallet-js/node_modules/grpc/src/client_interceptors.js:845:24)
initializing assets
#### aaaaa BEGIN ####
trying to create an asset: aaaaa#iroha (precision=18)
Error: Query response error: expected=ASSET_RESPONSE, actual=ERROR_RESPONSE
Reason: {"reason":1,"message":"query signatories did not pass validation","errorCode":3}
    at /root/iroha-wallet-js/node_modules/iroha-helpers/lib/queries/index.js:330:21
    at /root/iroha-wallet-js/node_modules/iroha-helpers/lib/queries/index.js:73:7
    at Object.onReceiveStatus (/root/iroha-wallet-js/node_modules/grpc/src/client_interceptors.js:1207:9)
    at InterceptingListener._callNext (/root/iroha-wallet-js/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/root/iroha-wallet-js/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/root/iroha-wallet-js/node_modules/grpc/src/client_interceptors.js:845:24)

Thank you!

**Comment by consultchwong** [comment]
The wrong thing is the admin@iroha.priv. This private key depends on your local iroha network. The github one is not the same one as your local one. Try to replace this with your local one. It may be found in /opt/iroha_data.
